server:
  port: 8040
spring:
  #定义服务的名称
  application:
    name: gateway-center
  #定义注册中心的地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8849
    gateway:
      discovery:
        locator:
          #让gateway通过服务发现组件发现其他微服务
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user_route
          uri: lb://user-center
          # 匹配由英文和数字组成的字符
          predicates:
            - CustomerTimeBetween=上午9:00,下午6:00





management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: trace
